apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-beginner
  labels:
    app: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app-container
        image: toolboxdevopsplayground/hello-world-nodejs:latest
        ports:
        - containerPort: 3000
