apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: python:3.9-slim
        command: ["sh", "-c", "pip install flask && python /app/app.py"]
        env:
        - name: FLASK_APP
          value: "app.py"
        volumeMounts:
        - name: app-volume
          mountPath: /app
        ports:
        - containerPort: 5000
      volumes:
      - name: app-volume
        configMap:
          name: hello-world-app
