apiVersion: v1
kind: Pod
metadata:
  name: test-client
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "sleep 3600"]


kubectl apply -f test-pod.yaml

kubectl exec -it test-client -- sh

wget -qO- http://hello-world-service:5000

