# Vagrantfile to provision a Kubernetes cluster with 1 master and 2 worker nodes
Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "10096" # Adjust to your desired memory size (e.g., 4096MB for 4GB)
  end
  # Define the Kubernetes nodes
  nodes = [
    { name: "master", memory: 3072, cpus: 2, script: "setup_master.sh", ip: "192.168.56.10" },
    { name: "worker1", memory: 2048, cpus: 2, script: "setup_worker.sh", ip: "192.168.56.12"  },
    { name: "worker2", memory: 2048, cpus: 2, script: "setup_worker.sh", ip: "192.168.56.11"  }
  ]
  
  nodes.each do |node|
    config.vm.define node[:name] do |vm|
      vm.vm.box = "ubuntu/focal64" # Ubuntu 20.04 LTS
      vm.vm.box_version = "20240821.0.1"
      vm.vm.hostname = node[:name]
      vm.vm.network "private_network", ip: node[:ip] # Usa IP fixo ao invés de DHCP
      vm.vm.provider "virtualbox" do |vb|
        vb.memory = node[:memory]
        vb.cpus = node[:cpus]
      end
      
      # Provisioning script
      vm.vm.provision "shell", path: "scripts/#{node[:script]}"
    end
  end
end
